<?php /** @var \Flagbit_Faq_Block_Frontend_Detail $this */ ?>
<?php $_faq = $this->getFaq() ?>

<?php if ($_faq): ?>
<div itemscope itemprop="mainEntity" itemtype="http://schema.org/Question">
    <div class="page-title">
        <h1 itemprop="name text"><?php echo $this->escapeHtml($_faq->getQuestion()) ?></h1>
    </div>

    <span style="display: none" itemprop="answerCount">1</span>

    <div class="faq-detail" itemprop="acceptedAnswer suggestedAnswer" itemscope itemtype="http://schema.org/Answer">>
        <p class="faq-date" itemprop="dateCreated">
            <?php echo Mage::getModel('core/date')->date('d.m.Y', $_faq->getPublicationTime()); ?>
        </p>

        <?php $_content = $_faq->getAnswerHtml() ? $_faq->getAnswer() : $this->escapeHtml($_faq->getAnswer()) ?>
        <?php if (!empty($_content)): ?>
        <div class="faq-content" itemprop="text">
            <?php if ($_faq->getAnswerHtml()): ?>
                <p><?php echo $this->helper('cms')->getPageTemplateProcessor()->filter($_content); ?></p>
            <?php else: ?>
                <?php foreach ( explode("\n", $_content) as $paragraph ): ?>
                    <p><?php echo $paragraph ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>

        <p><a href="<?php echo Mage::app()->getStore()->getUrl('faq') ?>" title="<?php echo $this->__('Back to the FAQ overview') ?>"><?php echo $this->__('Back to the FAQ overview') ?></a></p>
    </div>
</div>
<?php else: ?>
<div class="page-title">
    <h1><?php echo $this->__('Error') ?></h1>
</div>

<p><?php echo $this->__('The requested FAQ item could not be found!') ?></p>
<?php endif; ?>
